/**
 * Email Notification Service
 * Sends MRP run completion reports and shortage alerts
 */
import nodemailer from 'nodemailer';
import { config } from '../config';
import prisma from '../db';

let transporter: nodemailer.Transporter | null = null;

function getTransporter() {
  if (!transporter && config.smtp.host) {
    transporter = nodemailer.createTransport({
      host: config.smtp.host,
      port: config.smtp.port,
      secure: config.smtp.port === 465,
      auth: {
        user: config.smtp.user,
        pass: config.smtp.pass,
      },
    });
  }
  return transporter;
}

/**
 * Send MRP run completion report
 */
export async function sendRunCompletionReport(runId: number): Promise<void> {
  const mailer = getTransporter();
  if (!mailer || config.notifyEmails.length === 0) return;

  const run = await prisma.mrpRun.findUnique({ where: { id: runId } });
  if (!run) return;

  // Get summary stats
  const [totalParts, shortageParts] = await Promise.all([
    prisma.fgMonthly.count({ where: { mrpRunId: runId } }),
    prisma.fgMonthly.count({ where: { mrpRunId: runId, shouldPlanProduction: true } }),
  ]);

  const healthPct = totalParts > 0
    ? Math.round(((totalParts - shortageParts) / totalParts) * 100)
    : 100;

  const subject = `[MRP] Run ${run.versionCode} completed — ${shortageParts} shortages detected`;

  const html = `
    <div style="font-family: system-ui, sans-serif; max-width: 600px;">
      <h2 style="color: #1e293b;">MRP Run Completed</h2>
      <table style="border-collapse: collapse; width: 100%;">
        <tr>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: bold;">Version</td>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-family: monospace;">${run.versionCode}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: bold;">Run Date</td>
          <td style="padding: 8px; border: 1px solid #e2e8f0;">${new Date(run.runDate).toLocaleDateString('zh-TW')}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: bold;">Total Parts</td>
          <td style="padding: 8px; border: 1px solid #e2e8f0;">${totalParts}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: bold;">Shortages</td>
          <td style="padding: 8px; border: 1px solid #e2e8f0; color: ${shortageParts > 0 ? '#dc2626' : '#16a34a'}; font-weight: bold;">${shortageParts}</td>
        </tr>
        <tr>
          <td style="padding: 8px; border: 1px solid #e2e8f0; font-weight: bold;">Supply Health</td>
          <td style="padding: 8px; border: 1px solid #e2e8f0;">${healthPct}%</td>
        </tr>
      </table>
      ${shortageParts > 0 ? `
        <p style="margin-top: 16px; color: #dc2626;">
          ⚠ ${shortageParts} parts require production planning. Please review in the MRP dashboard.
        </p>
      ` : `
        <p style="margin-top: 16px; color: #16a34a;">
          ✅ All parts have adequate supply coverage.
        </p>
      `}
      <p style="margin-top: 16px; color: #64748b; font-size: 12px;">
        Generated by Funda MRP System
      </p>
    </div>
  `;

  await mailer.sendMail({
    from: config.smtp.from,
    to: config.notifyEmails.join(','),
    subject,
    html,
  });
}

/**
 * Send shortage alert for specific parts
 */
export async function sendShortageAlert(runId: number): Promise<void> {
  const mailer = getTransporter();
  if (!mailer || config.notifyEmails.length === 0) return;

  const shortageParts = await prisma.fgMonthly.findMany({
    where: { mrpRunId: runId, shouldPlanProduction: true },
    orderBy: { shortageStartPeriod: 'asc' },
    take: 50,
  });

  if (shortageParts.length === 0) return;

  const run = await prisma.mrpRun.findUnique({ where: { id: runId } });
  const subject = `[MRP Alert] ${shortageParts.length} parts with shortages — ${run?.versionCode || runId}`;

  const rows = shortageParts
    .map(
      (p: (typeof shortageParts)[number]) => `
        <tr>
          <td style="padding: 6px 8px; border: 1px solid #e2e8f0; font-family: monospace; font-size: 12px;">${p.partVersion}</td>
          <td style="padding: 6px 8px; border: 1px solid #e2e8f0; font-size: 12px;">${p.customerCode || '—'}</td>
          <td style="padding: 6px 8px; border: 1px solid #e2e8f0; text-align: right; font-family: monospace;">${Number(p.currentStockPc).toLocaleString()}</td>
          <td style="padding: 6px 8px; border: 1px solid #e2e8f0; text-align: center; color: #dc2626; font-weight: bold;">M${(p.shortageStartPeriod || 0) + 1}</td>
        </tr>
      `,
    )
    .join('');

  const html = `
    <div style="font-family: system-ui, sans-serif; max-width: 700px;">
      <h2 style="color: #dc2626;">⚠ Shortage Alert</h2>
      <p style="color: #64748b;">${shortageParts.length} parts require immediate attention.</p>
      <table style="border-collapse: collapse; width: 100%; margin-top: 12px;">
        <thead>
          <tr style="background: #f1f5f9;">
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Part Version</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: left;">Customer</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: right;">Stock</th>
            <th style="padding: 8px; border: 1px solid #e2e8f0; text-align: center;">Shortage At</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="margin-top: 16px; color: #64748b; font-size: 12px;">
        Generated by Funda MRP System
      </p>
    </div>
  `;

  await mailer.sendMail({
    from: config.smtp.from,
    to: config.notifyEmails.join(','),
    subject,
    html,
  });
}
