import test from 'node:test';
import assert from 'node:assert/strict';
import { NextRequest } from 'next/server';
import { GET, POST, PATCH, PUT } from '@/app/demo-api/[...path]/route';
import { dataset } from './data';
import { prepareDemo } from './run-control';
import { latestRun, state } from './store';
import { archiveRuns } from './archive';
import { warehouseDetail } from './details';
import { adaptArchiveFgReport } from '../archive/fg-report-adapter';
import { adaptArchiveWeeklyReport } from '../archive/weekly-report-adapter';
let generatedTransferId: number;

async function query(method: 'GET' | 'POST' | 'PATCH' | 'PUT', path: string, body?: unknown) {
  const url = new URL(`http://127.0.0.1:3142/demo-api/${path}`);
  const request = new NextRequest(url, { method, ...(body !== undefined ? { body: JSON.stringify(body), headers: { 'Content-Type': 'application/json' } } : {}) });
  const response = await ({ GET, POST, PATCH, PUT }[method])(request, { params: Promise.resolve({ path: url.pathname.slice('/demo-api/'.length).split('/') }) });
  return { status: response.status, body: await response.json() };
}
test.before(async () => prepareDemo());
test('歷史清單、原版 adapters、Run 身分反例與唯讀拒絕', async () => {
  const list = await query('GET', 'archive/runs?page=2');
  assert.equal(list.status, 200); assert.equal(list.body.total, 64); assert.equal(list.body.runs.length, 14);
  for (const run of [archiveRuns[0], archiveRuns[63]]) {
    const fg = await query('GET', `archive/runs/${run.id}/fg-report`);
    const adapted = adaptArchiveFgReport(fg.body);
    assert.equal(adapted.items.length, 48); assert.equal(fg.body.run.sourceRunId, run.sourceRunId);
    const aggregate = await query('GET', `archive/runs/${run.id}/fg-report?aggregated=true`);
    assert.equal(adaptArchiveFgReport(aggregate.body).items.length, 24);
    const weekly = await query('GET', `archive/runs/${run.id}/weekly-report?kind=component&mrpType=B`);
    assert.equal(adaptArchiveWeeklyReport(weekly.body).componentItems.length, 12);
    const sales = await query('GET', `archive/runs/${run.id}/weekly-report?kind=sales`);
    assert.equal(adaptArchiveWeeklyReport(sales.body).salesItems.length, 48);
    fg.body.periods[0].mrp_run_id = '999';
    assert.throws(() => adaptArchiveFgReport(fg.body), /不一致/);
    assert.equal((await query('POST', `archive/runs/${run.id}`)).status, 405);
  }
  const run = archiveRuns[0];
  assert.equal((await query('GET', `fg-material-reminders?archiveId=${run.id}&runId=3&targets=[]`)).status, 409);
  assert.equal((await query('PATCH', `fg-monthly/XA-PRODUCT-001-R1/suggestions?archiveId=${run.id}`, { planSequence: 1, suggestedQty: 100 })).status, 405);
});
test('原明細、共享庫存、需求歸屬、元件用量按同一合成快照對帳', async () => {
  const runId = latestRun().id;
  const source = await query('GET', `fg-monthly/XA-PRODUCT-001-R1/sources?runId=${runId}`);
  assert.equal(source.status, 200); assert.equal(source.body.orders.length, 12);
  assert.equal(source.body.inventory[0].goodStockPc, 2090);
  const first = await query('GET', `fg-monthly/XA-PRODUCT-001-R1/source-records?runId=${runId}&type=orders&periodIndex=0`);
  assert.equal(first.body.records.length, 1); assert.equal(first.body.summary.outstandingOrderQty, first.body.records[0].unshippedQty);
  const warehouse = await query('GET', `fg-monthly/warehouse-stock?runId=${runId}&partVersion=XA-PRODUCT-001-R1&warehouse=INTERNAL`);
  assert.equal(warehouse.status, 200); assert.equal(warehouse.body.totalPc, 1590);
  assert.equal(warehouse.body.qualitySummaries[0].qualityStatus, warehouse.body.lots[0].qualityStatus);
  const excludedData = structuredClone(dataset(runId));
  const excludedLot = excludedData.source.inventory_lots.find((row) => row.erpPartNo === 'DEMO-FG-001-V01' && row.warehouseCode === 'HD')!;
  excludedLot.qualityStatus = '不良';
  const excluded = warehouseDetail(excludedData, new URLSearchParams('partVersion=XA-PRODUCT-001-R1&warehouse=INTERNAL')) as { availablePc: number; excludedPc: number; lots: { includedInMrp: boolean }[] };
  assert.equal(excluded.availablePc, 0); assert.equal(excluded.excludedPc, 1590); assert.equal(excluded.lots[0].includedInMrp, false);
  const usage = await query('GET', `component-weekly/DEMO-W-001/usage-details?runId=${runId}&mrpType=W&weekIndex=all`);
  assert.equal(usage.status, 200); assert.equal(usage.body.reconciled, true); assert.ok(usage.body.includedTotal > 0);
  assert.ok(usage.body.weeklyProjection.every((row: { difference: number }) => row.difference === 0));
  assert.equal(usage.body.purchaseOrders[0].arrivesAfterShortage, true);
  assert.equal(usage.body.purchaseOrders[0].requiresExpedite, true);
  assert.equal(usage.body.materialSummary.expeditePurchaseQty, 180);
  const otherWeek = await query('GET', `component-weekly/DEMO-W-001/usage-details?runId=${runId}&mrpType=W&weekIndex=3`);
  assert.equal(otherWeek.body.purchaseOrders[0].inSelectedScope, false);
  assert.equal(otherWeek.body.materialSummary.supplyQty, 0);
  const partialUsage = await query('GET', `component-weekly/DEMO-B-003/usage-details?runId=${runId}&mrpType=B&weekIndex=all`);
  assert.equal(partialUsage.body.materialSummary.netIssuedQty, 1500);
  assert.equal(partialUsage.body.materialSummary.reservedQty, 1500);
  const unknownUsage = await query('GET', `component-weekly/DEMO-W-002/usage-details?runId=${runId}&mrpType=W&weekIndex=all`);
  assert.equal(unknownUsage.body.materialSummary.remainingUsage, null);
  const sales = await query('GET', `sales-meeting/XA-PRODUCT-001-R1/source-records?runId=${runId}&type=balance&scope=all`);
  const poolOrders = dataset(runId).source.orders.filter((row) => ['XA-PRODUCT-001-R1', 'XB-PRODUCT-001-R1'].includes(String(row.partVersion)));
  assert.equal(sales.body.summaryBalance.remainingStock, 2090 - poolOrders.reduce((sum, row) => sum + Number(row.unshippedQty), 0));
  assert.equal(sales.body.summaryBalance.includesProductionPlans, false);
});
test('PUT 原方法、存單轉單去重、工令建立與多個 consumer 的權威狀態一致', async () => {
  const runId = latestRun().id, part = 'XA-PRODUCT-001-R1';
  const uncertain = state().suggestions.find((row) => row.mrpRunId === runId && row.transferStatus === 'unknown' && state().transfers.some((plan) => plan.mrpRunId === runId && plan.partVersion === row.partVersion && plan.planSequence === row.planSequence))!;
  const inspected = await query('POST', `fg-monthly/${uncertain.partVersion}/suggestions/reconcile`, { runId, planSequence: uncertain.planSequence, action: 'inspect' });
  assert.equal(inspected.status, 200); assert.equal(inspected.body.inspection.matchStatus, 'single_match');
  assert.equal(typeof inspected.body.inspection.candidates[0].suggestedQty, 'number');
  assert.doesNotThrow(() => inspected.body.inspection.candidates[0].suggestedQty.toLocaleString());
  assert.equal((await query('PUT', 'fg-monthly/ignored-customers', { codes: [' xa ', 'XA'] })).status, 200);
  assert.deepEqual((await query('GET', 'fg-monthly/ignored-customers')).body.codes, ['XA']);
  await query('PUT', 'fg-monthly/ignored-customers', { codes: [] });
  const saved = await query('PATCH', `fg-monthly/${part}/suggestions`, { runId, planSequence: 1, suggestedQty: 1000, completionDate: '2026-09-30', targetStartPeriod: 1, fulfillToPeriod: 3, bufferPct: 0.1 });
  assert.equal(saved.status, 200); assert.equal(saved.body.useManualQty, true);
  const transferred = await query('PATCH', `fg-monthly/${part}/suggestions`, { runId, planSequence: 1, isTransferred: true, returnSuggestions: true });
  assert.equal(transferred.status, 200); assert.equal(transferred.body.isTransferred, true);
  const again = await query('PATCH', `fg-monthly/${part}/suggestions`, { runId, planSequence: 1, isTransferred: true });
  assert.equal(again.body.transferId, transferred.body.transferId);
  const transfers = (await query('GET', `production-plans?runId=${runId}`)).body.transfers;
  assert.equal(transfers.filter((row: { partVersion: string; planSequence: number }) => row.partVersion === part && row.planSequence === 1).length, 1);
  const id = transferred.body.transferId;
  generatedTransferId = id;
  const created = await query('POST', `production-plans/${id}/work-orders`);
  assert.equal(created.status, 202); assert.equal(created.body.workOrderStatus, 'queued');
  assert.equal((await query('POST', `production-plans/${id}/work-orders`)).status, 409);
  await new Promise((resolve) => setTimeout(resolve, 350));
  assert.equal((await query('GET', `production-plans/${id}/work-orders`)).body.workOrderStatus, 'succeeded');
  await query('PATCH', 'fg-monthly/XA-PRODUCT-003-R1/suggestions', { runId, planSequence: 1, suggestedQty: 2000, completionDate: '2026-09-30' });
  const other = await query('PATCH', 'fg-monthly/XA-PRODUCT-003-R1/suggestions', { runId, planSequence: 1, isTransferred: true });
  assert.equal((await query('POST', `production-plans/${other.body.transferId}/work-orders`)).status, 202);
  await new Promise((resolve) => setTimeout(resolve, 350));
  const otherArtifact = (await query('GET', `production-plans/${other.body.transferId}/work-orders`)).body.workOrderResponse;
  const newBom = otherArtifact.bom.find((row: { componentNo: string }) => row.componentNo === 'DEMO-B-003');
  assert.equal(newBom.remainingUsage, 2000); assert.equal(newBom.netIssuedQty, 0); assert.equal(newBom.reservedQty, 0);
  const plans = (await query('GET', `plan-management?runId=${runId}`)).body.items;
  assert.equal(plans.find((row: { transferId: number }) => row.transferId === id).workOrderStatus, 'succeeded');
  assert.equal((await query('PATCH', `fg-monthly/${part}/suggestions`, { runId: 1, planSequence: 1, suggestedQty: 100 })).status, 409);
});
test('主檔更新不改快照；暫停、停止、續算與晚到結果不污染 latest', async () => {
  const oldId = latestRun().id, before = JSON.stringify(dataset(oldId));
  const data = dataset(oldId), inv = data.source.inventory.find((row) => row.erpPartNo === 'DEMO-W-001')!;
  const current = state().leadTimes['DEMO-W-001'] ?? Number(inv.purchaseLeadWeeks);
  const changed = await query('PATCH', `component-weekly/DEMO-W-001/purchase-lead-time?runId=${oldId}&mrpType=W`, { ragicRecordId: inv.ragicRecordId, expectedPurchaseLeadWeeks: current, expectedConfigured: true, purchaseLeadWeeks: current + 1 });
  assert.equal(changed.status, 200); assert.equal(JSON.stringify(dataset(oldId)), before);
  assert.equal((await query('PATCH', 'component-weekly/DEMO-W-001/purchase-lead-time?runId=1&mrpType=W', { ragicRecordId: inv.ragicRecordId, expectedPurchaseLeadWeeks: current + 1, expectedConfigured: true, purchaseLeadWeeks: current + 2 })).status, 409);
  const started = await query('POST', 'runs', {}), id = started.body.runId;
  assert.equal(started.status, 202);
  assert.equal((await query('POST', 'runs', {})).status, 409);
  assert.equal((await query('PATCH', `component-weekly/DEMO-W-001/purchase-lead-time?runId=${oldId}&mrpType=W`, { ragicRecordId: inv.ragicRecordId, expectedPurchaseLeadWeeks: current + 1, expectedConfigured: true, purchaseLeadWeeks: current + 2 })).status, 409);
  assert.equal((await query('POST', `runs/${id}/signal`, { action: 'pause' })).status, 200);
  await new Promise((resolve) => setTimeout(resolve, 300));
  assert.equal((await query('GET', 'runs/active')).body.runId, id);
  await query('POST', `runs/${id}/signal`, { action: 'stop' });
  await new Promise((resolve) => setTimeout(resolve, 250));
  assert.equal(latestRun().id, oldId); assert.equal(state().snapshots[String(id)], undefined);
  assert.equal((await query('POST', `runs/${id}/resume`)).status, 202);
  for (let attempt = 0; attempt < 30 && state().runs.find((run) => run.id === id)?.status === 'calculating'; attempt++) await new Promise((resolve) => setTimeout(resolve, 100));
  assert.equal(latestRun().id, id);
  assert.equal(dataset(id).cw.find((row) => row.materialPartNo === 'DEMO-W-001')?.purchaseLeadWeeks, current + 1);
  assert.equal(JSON.stringify(dataset(oldId)), before);
  const generatedNumber = `DEMO-GENERATED-WO-${generatedTransferId}`;
  assert.equal(dataset(id).source.work_orders.find((row) => row.woNumber === generatedNumber)?.woQty, 1000);
  const generatedBom = dataset(id).source.work_order_bom.filter((row) => row.woNumber === generatedNumber);
  assert.equal(generatedBom.length, 3);
  assert.equal(generatedBom.find((row) => row.componentNo === 'DEMO-B-001')?.remainingUsage, 1000);
  const expected = dataset(id).source.work_order_bom.filter((row) => row.componentNo === 'DEMO-B-001' && row.issuedQtyState !== 'unknown').reduce((sum, row) => sum + Number(row.remainingUsage ?? row.minUsage), 0);
  assert.equal(dataset(id).cwPeriods['DEMO-B-001'].reduce((sum, row) => sum + Number(row.usage), 0), expected);
  const suggestionsBefore = JSON.stringify(state().suggestions);
  assert.equal((await query('PATCH', 'fg-monthly/XA-PRODUCT-001-R1/suggestions', { runId: oldId, planSequence: 1, suggestedQty: 99 })).status, 409);
  assert.equal((await query('PATCH', 'fg-monthly/XA-PRODUCT-001-R1/suggestions', { planSequence: 1, suggestedQty: 99 })).status, 409, 'RUN_ORIGIN_REQUIRED');
  assert.equal(JSON.stringify(state().suggestions), suggestionsBefore);
  const previous = structuredClone(state().suggestions.filter((row) => row.mrpRunId === oldId));
  const target = state().suggestions.find((row) => row.mrpRunId === id && row.partVersion === 'XA-PRODUCT-001-R1')!;
  assert.equal((await query('POST', 'fg-monthly/XA-PRODUCT-001-R1/suggestions/reconcile', { runId: id, planSequence: target.planSequence, action: 'confirm_not_created' })).status, 200);
  assert.deepEqual(state().suggestions.filter((row) => row.mrpRunId === oldId), previous);
  assert.equal(state().suggestions.find((row) => row.mrpRunId === id && row.partVersion === target.partVersion && row.planSequence === target.planSequence)?.transferStatus, 'failed');
});
